### ISSUE TITLE
Error while generating the template solution

### ISSUE THREAD

**Issue by VenkateshSrini** [adrianhall/generator-azure-mobile-apps#8]
HI,
When trying to generate the solution using Yoman, we are facing the attached solution. Could some one provide some insights on the same?
[npm-debug.txt](https://github.com/adrianhall/generator-azure-mobile-apps/files/174104/npm-debug.txt)

 I have attached the debug log generated with solution generation process along with this issue.
Thanks and regards
Venkatesh

**Comment by adrianhall** [comment]
grep for error - you see that you don't have git installed.

**Comment by VenkateshSrini** [comment]
I'm on windows 10. Could you please send me the link for Git

-----Original Message-----
